"""Agent Card 必须符合 A2A 线上格式。

★ 这条测试的由来：contactor 原来把字段写成了 snake_case
  （default_input_modes / security_schemes），路径对了但内容不兼容 ——
  别的 A2A 实现来读会拿不到这些字段。教案 4.1 给了字段表，照它定死。
"""
from __future__ import annotations
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parents[1] / "src"))

import pytest
from contactor.backends.subprocess_cli import SubprocessCliBackend
from contactor.domain.models import AgentCapabilities, AgentCard, Skill

# 教案 4.1 的字段表
SPEC_FIELDS = ["protocolVersion", "name", "description", "url", "preferredTransport",
               "version", "provider", "capabilities",
               "defaultInputModes", "defaultOutputModes", "skills", "securitySchemes"]

# capabilities 里前三个是 A2A 规范键；后两个是本桥扩展（显式声明，别混）
SPEC_CAPS = ["streaming", "pushNotifications", "stateTransitionHistory"]
BRIDGE_CAPS = ["inputRequired", "contentVerified"]


def test_wire_names_are_camel_case():
    """线上字段名必须是 camelCase —— 这是 A2A 的格式，不是风格偏好。"""
    d = AgentCard(name="x").model_dump()
    for f in SPEC_FIELDS:
        assert f in d, f"名片缺字段 {f}"
    snake = [k for k in d if "_" in k]
    assert not snake, f"这些字段还是 snake_case：{snake}"


def test_capabilities_is_an_object_with_spec_keys():
    caps = AgentCapabilities()
    for k in SPEC_CAPS:
        assert hasattr(caps, k), f"capabilities 缺规范键 {k}"
    for k in BRIDGE_CAPS:
        assert hasattr(caps, k), f"capabilities 缺本桥扩展键 {k}"


def test_skills_declare_business_capability_not_a_name():
    """★ 教案 5.3 点名的翻车点。

    skills 写成「委托给 dsh」= 名字粒度 → 编排器无法判断"适不适合接这个活"，
    而且暴露内部实现。技能必须是【业务语义】。
    """
    be = SubprocessCliBackend(
        "demo", [sys.executable, "-c", "print(1)"],
        description="跑一次性命令",
        skills=[Skill(id="code-run", name="执行代码",
                      description="在沙箱里跑一段脚本并回结果",
                      examples=["跑个 pytest"])])
    import asyncio
    card = asyncio.run(be.card())
    assert card.skills, "配置给了 skills，名片上就该有"
    s = card.skills[0]
    assert s.id == "code-run" and s.description and s.examples
    # 反例：id/name 就等于 agent 名字 = 名字粒度
    assert s.id != "demo", "skills 不该是 agent 名字的复读"
    assert "委托给" not in s.description, "技能描述不该是「委托给 X」"


def test_no_skill_means_empty_not_autogenerated():
    """没配 skills 就留空 —— 不要自动生成一个没信息量的。"""
    be = SubprocessCliBackend("bare", [sys.executable, "-c", "print(1)"])
    import asyncio
    assert asyncio.run(be.card()).skills == []
